import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useMCPs } from './hooks/useMCPs';
export default function App() {
    const [activeTab, setActiveTab] = useState('mcps');
    const { groups, plugins, skills, toggleMCP, toggleGroup } = useMCPs();
    return (_jsxs("div", { className: "min-h-screen bg-slate-950 text-slate-100", children: [_jsx("header", { className: "border-b border-slate-800 bg-slate-900/50 backdrop-blur", children: _jsxs("div", { className: "max-w-7xl mx-auto px-6 py-4", children: [_jsx("h1", { className: "text-2xl font-bold", children: "MCP Gateway Controller" }), _jsx("p", { className: "text-sm text-slate-400 mt-1", children: "Unified MCP management for all your tools" })] }) }), _jsx("div", { className: "border-b border-slate-800 bg-slate-900/30 sticky top-0 z-10", children: _jsx("div", { className: "max-w-7xl mx-auto px-6", children: _jsx("nav", { className: "flex gap-8", children: ['mcps', 'plugins', 'skills'].map((tab) => (_jsx("button", { onClick: () => setActiveTab(tab), className: `py-4 px-1 border-b-2 font-medium transition ${activeTab === tab
                                ? 'border-blue-500 text-blue-400'
                                : 'border-transparent text-slate-400 hover:text-slate-300'}`, children: tab.charAt(0).toUpperCase() + tab.slice(1) }, tab))) }) }) }), _jsxs("main", { className: "max-w-7xl mx-auto px-6 py-8", children: [activeTab === 'mcps' && (_jsx("div", { className: "space-y-6", children: Object.entries(groups).map(([groupName, group]) => (_jsxs("div", { className: "bg-slate-900 border border-slate-800 rounded-lg overflow-hidden", children: [_jsxs("div", { className: "bg-slate-800/50 px-6 py-4 flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h2", { className: "font-semibold text-lg", children: groupName }), _jsxs("p", { className: "text-sm text-slate-400 mt-1", children: [group.enabledCount, " of ", group.totalCount, " enabled"] })] }), _jsx("button", { onClick: () => toggleGroup(groupName), className: `px-4 py-2 rounded font-medium transition ${group.enabled
                                                ? 'bg-blue-600 hover:bg-blue-700 text-white'
                                                : 'bg-slate-700 hover:bg-slate-600 text-slate-300'}`, children: group.enabled ? 'Disable All' : 'Enable All' })] }), _jsx("div", { className: "divide-y divide-slate-800", children: group.mcps.map((mcp) => (_jsxs("div", { className: "px-6 py-4 flex items-center justify-between hover:bg-slate-800/50 transition", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-medium", children: mcp.name }), mcp.hasCliAvailable && (_jsxs("p", { className: "text-xs text-green-400 mt-1", children: ["\u2713 CLI available", mcp.hasCliInstalled && ' • CLI installed'] }))] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: `text-xs font-medium px-2 py-1 rounded ${mcp.enabled
                                                            ? 'bg-green-900/30 text-green-400'
                                                            : 'bg-slate-800 text-slate-400'}`, children: mcp.enabled ? 'Active' : 'Inactive' }), _jsx("button", { onClick: () => toggleMCP(mcp.name), className: `w-12 h-6 rounded-full transition ${mcp.enabled
                                                            ? 'bg-green-600'
                                                            : 'bg-slate-700'}`, "aria-label": `Toggle ${mcp.name}` })] })] }, mcp.name))) })] }, groupName))) })), activeTab === 'plugins' && (_jsx("div", { className: "grid gap-4", children: plugins.map((plugin) => (_jsxs("div", { className: "bg-slate-900 border border-slate-800 rounded-lg px-6 py-4 flex items-center justify-between", children: [_jsx("h3", { className: "font-medium", children: plugin.name }), _jsx("span", { className: `text-xs font-medium px-2 py-1 rounded ${plugin.enabled
                                        ? 'bg-green-900/30 text-green-400'
                                        : 'bg-slate-800 text-slate-400'}`, children: plugin.enabled ? 'Enabled' : 'Disabled' })] }, plugin.name))) })), activeTab === 'skills' && (_jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: skills.map((skill) => (_jsxs("div", { className: "bg-slate-900 border border-slate-800 rounded-lg px-6 py-6", children: [_jsx("h3", { className: "font-semibold text-lg", children: skill.name }), _jsx("p", { className: "text-slate-400 text-sm mt-2", children: skill.description }), _jsx("p", { className: "text-blue-400 text-xs font-mono mt-4 bg-slate-800 px-3 py-2 rounded", children: skill.command })] }, skill.name))) }))] })] }));
}
